[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


# Netlify Secrets Scanning configuration
# We explicitly omit benign keys that are expected to appear in code/output.
# Do NOT omit real secrets like SUPABASE_SERVICE_ROLE_KEY.
[secrets_scan]
  omit_keys = ["MEDIA_BUCKET", "DOCUMENTS_BUCKET"]

# Use a stable Node version for builds
[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_RETRY = "5"
  NPM_CONFIG_FETCH_RETRIES = "5"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "10000"
  NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "60000"
  NPM_CONFIG_NETWORK_TIMEOUT = "600000"
  NPM_CONFIG_PROGRESS = "false"


