[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


# Netlify Secrets Scanning configuration
# We explicitly omit benign keys that are expected to appear in code/output.
# Do NOT omit real secrets like SUPABASE_SERVICE_ROLE_KEY.
[secrets_scan]
  omit_keys = ["MEDIA_BUCKET", "DOCUMENTS_BUCKET"]


